version: '2.2'
services:
  discovery:
    container_name: discovery
    image: discovery:latest
    ports:
      - 8761:8761
    healthcheck:
      test: "exit 0"
  config:
    container_name: config
    image: config:latest
    ports:
      - 8888:8888
    healthcheck:
      test: "exit 0"
    depends_on:
      discovery:
        condition: service_healthy
  gateway:
    container_name: gateway
    image: gateway:latest
    ports:
      - 9099:9099
    healthcheck:
      test: "exit 0"
    depends_on:
      discovery:
        condition: service_healthy
      config:
        condition: service_healthy

